import { Inter } from 'next/font/google'
import Nav from './Nav/page'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (<>
   
    <html lang="en">
 
      <body className={inter.className}>
      <ul className='flex m-0 p-0 border-2 justify-end ' >
    <Link href="/"><li className="text-center text-blue-500 mx-5">Home</li></Link>
    <Link href="/About"> <li className='mx-5'>About</li></Link>
    <li className='mx-5'>About</li>
    <li className='mx-5'>Contact</li>
    </ul>
    {children}
      </body>
    </html>
    </>
  )
}
